#!/bin/sh

VERSION=v2.0

VT=$(tty | sed 's/^.*tty/vt/g')

trysource() {
	test -f "$1" -a -r "$1" && source "$1"
}

if [ "$1" ]; then
	if [ "$1" = xlaunch ]; then
		command="$2"
		cd $HOME
		trysource ./.xprofile || trysource /etc/xprofile
		$command
		cd $HOME
		trysource ./.xlogout || trysource /etc/xlogout
		exit
	else
		trysource $1 || shift
	fi
fi
if [ ! "$1" ]; then
	trysource $HOME/.scdmrc || trysource /etc/scdmrc || \
		{ echo "ERROR: no config file!"; exit 1; }
fi

SESSIONS="$(printf '%s\n%s\n' "$SESSIONS" "Exit:C:true" | sed -e '/^\s*$/d' -e 's/^\s*//')"
SESS_NUM="$(echo "$SESSIONS" | wc -l)"

LINE=--------------------------------------------------------------------------------
echo -e "\n$(basename $0) $VERSION\n$LINE\nSelect a session:\n" \

select session in "${SESS_NAMES[@]}"; do
	if [ -z "$session" -o $REPLY -gt $SESS_NUM ] 2> /dev/null || [ $? = 2 ]; then
		echo -e "\nYou must specify a number between 1 and $SESS_NUM!\n" >&2
	else
		break
	fi
done
unset session

SESSION="$(echo "$SESSIONS" | sed -n "${n}p")"

TYPE=${SESSION#*:}
TYPE=${TYPE%:*}
CMD=${SESSION##*:}

export SCDM_SPAWN=$$
clear
if [ "${TYPE/X/x}" = x ]
then
	cd $(dirname $0)
	exec startx $PWD/$(basename $0) xlaunch "$CMD" -- "$XSERVER_ARGS" $VT > /dev/null 2>&1
else
	cd $HOME
	exec $CMD
fi
