.Dd June 20, 2018
.Dt SCDM 1
.Sh NAME
.Nm scdm
.Nd simple console display manager
.\" END NAME
.Sh SYNOPSIS
.Nm
.Op Ar rcfile
.\" END SYNOPSIS
.Sh DESCRIPTION
.Nm
is a login manager for the console. It can be used instead of DM's
like xdm, kdm etc. to choose and start terminal or X11 sessions.
.Pp
For
.Nm
to be automatically launched on tty logins simply copy
the launcher script
.Pq see Sx FILES
to
.Pa /etc/profile.d/
and/or make sure
it is sourced by
.Pa /etc/profile
or
.Pa ~/.*profile
after everything else
.Pq because it uses exec .
.\" END DESCRIPTION
.Sh FILES
.Bl -item -compact
.It
.Ar rcfile
.It
.Pa ~/.scdmrc
.It
.Pa /etc/scdmrc
.El
.D1 Configuration files. The first existing one is used. \
For a documented example consult the example file \
Pq Pa /etc/scdmrc .
.Pp
.Bl -item -compact
.It
.Pa /etc/profile.d/scdm.sh
.It
.Pa /usr/local/share/scdm/profile.sh
.El
.D1 Launcher script and example.
.Pp
.Bl -item -compact
.It
.Pa ~/.xprofile
.It
.Pa /etc/xprofile
.It
.Pa ~/.xlogout
.It
.Pa /etc/xlogout
.El
.D1 Like Pa ~/.profile No or Pa ~/.bash_logout , No only for X sessions.
.\" END FILES
.Sh AUTHORS
Copyright (c) 2013\[en]2018
.An Johannes Rosenberger Aq Mt johannes.rosenberger@jorsn.eu .
This program is licensed under a BSD style 3\-clause license.
.\" END AUTORS
.Sh BUGS
If you encounter any or would like additional features, please send a mail to
the author or create an issue at
.Lk https://github.com/jorsn/scdm/issues .
.\" END BUGS
