#!/bin/sh

###### Start X11 Session? ######

trysource() {
#shellcheck source=./scdmrc
	test -f "$1" -a -r "$1" && . "$1"
}

if [ -n "${COMMAND}" ]
then
	comm="$COMMAND"
	unset COMMAND
#shellcheck disable=SC2164
# disable warning about cd failure
	cd "$HOME"
        trysource "$HOME/.xprofile" || trysource /etc/xprofile
        $comm
        #shellcheck disable=SC2164
        cd "$HOME"
        trysource "$HOME/.xlogout" || trysource /etc/xlogout
	exit
fi


###### The real program ######

SELF="$(basename "$0")"

VERSION=v2.0

VT="$(tty | sed 's/^.*tty\([0-9]\+\)$/vt\1/g')"

fail() {
	fmt="$1"
	shift
	printf "\n%s$fmt\n\n" "$SELF: ERROR: " "$@" >&2
	exec "$(sed -n "s/^$USER:.\+://gp" /etc/passwd)"
}

usage() {
	echo "Usage: $(basename "$0") [rcfile]" >&2
	exit "$1"
}

printsessions() {
	echo "$PRINTSESSIONS"
}

if [ $# -gt 1 ]
then
	usage 1
elif [ $# -eq 1 ]
then
	if [ "$1" = -h ] || [ "$1" = --help ]
	then
		usage 0
	elif ! trysource "$1"
	then
		shift
		unset SESSIONS XSERVER_ARGS
	fi
fi
if [ -z "$1" ]; then
	trysource "$HOME/.scdmrc" || trysource /etc/scdmrc || \
		fail "no config file!"
fi

SESSIONS="$(printf '%s\n%s\n' "$SESSIONS" "Exit:C:true" \
	     | sed -n -e '/^\s*$/d' -e 's/^\s*//g' \
	              -e '/^\s*[^:]\+:[XxCc]:[^:]\+\s*$/{p;d}' -e 's/^/\t  =>\t/gp')"

# check for correctness of SESSIONS
if echo "$SESSIONS" | grep -q '^\s\+=>\s\+'
then
	fail 'configuration corrupt:\n\tin SESSION="\n%s\n\t\t"' \
		"$(echo "$SESSIONS" | sed -e '/^\s\+=>\t/{p;d}' -e 's/^/\t\t/g')"
fi


SESS_NUM="$(echo "$SESSIONS" | wc -l)"
PRINTSESSIONS="$(echo ''; \
	echo "$SESSIONS" | awk -F : "{printf \"%${SESS_NUM}i)  %-s\n\",NR,\$1}"; \
	echo ' ')"

LINE=--------------------------------------------------------------------------------
printf "\n%s %s\n%s\nSelect a session:\n" "$SELF" "$VERSION" "$LINE"

printsessions

i=0
while true
do
	if [ $i -ge 7 ]
	then
		printsessions
		i=0
	else
		i=$((i+1))
	fi
	printf '%s ' "${PS3:=>}"
	read -r n
	if [ -n "$n" ] && [ 1 -le "$n" ] && [ "$n" -le "$SESS_NUM" ]
	then
		break
	else
		printf "You must specify a number between 1 and %s!\n" "$SESS_NUM" >&2
	fi
done

SESSION="$(echo "$SESSIONS" | sed -n "${n}p")"

TYPE="${SESSION#*:}"
TYPE="${TYPE%:*}"
COMMAND="${SESSION##*:}"

export SCDM_SPAWN=$$
clear
printf 'Starting %s...\n' "${SESSION%%:*}"
if [ "$TYPE" = X ] || [ "$TYPE" = x ]
then
	export COMMAND
	exec startx "$(which "$0")" -- "$XSERVER_ARGS" "$VT" > /dev/null 2>&1
else
	cd "$HOME" || fail 'could not cd to: %s' "$HOME"
#shellcheck disable=SC2086
# do not complain about missing quotes
	exec $COMMAND
fi
