#!/bin/bash

VERSION=v1.1

VT=$(tty | sed 's/^.*tty/vt/g')

trysource() {
	test -f "$1" -a -r "$1" && source "$1"
}

if [ "$1" ]; then
	if [ "$1" = xlaunch ]; then
		command="$2"
		cd $HOME
		trysource ./.xprofile || trysource /etc/xprofile
		$command
		cd $HOME
		trysource ./.xlogout || trysource /etc/xlogout
		exit
	else
		trysource $1 || shift
	fi
fi
if [ ! "$1" ]; then
	trysource $HOME/.scdmrc || trysource /etc/scdmrc || \
		{ echo "ERROR: no config file!"; exit 1; }
fi

SESSIONS[${#SESSIONS[@]}]="Exit:C:true"
SESS_NUM=${#SESSIONS[@]}

for i in ${!SESSIONS[@]}; do
	SESS_NAMES[$i]=${SESSIONS[$i]%%:*}
done


LINE=--------------------------------------------------------------------------------
echo -e "\n$(basename $0) $VERSION\n$LINE\nSelect a session:\n" \

select session in "${SESS_NAMES[@]}"; do
	if [ -z "$session" -o $REPLY -gt $SESS_NUM ] 2> /dev/null || [ $? = 2 ]; then
		echo -e "\nYou must specify a number between 1 and $SESS_NUM!\n" >&2
	else
		break
	fi
done
unset session

SESS_STR=${SESSIONS[$[REPLY-1]]}

TYPE=${SESS_STR#*:}
TYPE=${TYPE%:*}
CMD=${SESS_STR##*:}

#echo -e "\nStarting ${SESSION[name]}..."
export SCDM_SPAWN=$$
clear
if [ "${TYPE/X/x}" = x ]; then
	#cd $(dirname $0)
	exec startx $PWD/$0 xlaunch "$CMD" -- "${XSERVER_ARGS[@]}" $VT > /dev/null 2>&1
else
	exec ${SESSION[cmd]}
fi
