#!/bin/sh


SESSIONS=(
	'XMonad:X:xmonad'
	'dwm:X:dwm'
	'i3:X:i3'
	'wmii:X:wmii'
	'Fluxbox:X:startfluxbox'
	'TMux:C:tmux'
	'Screen:C:screen'
	'Console:C:bash --login'
	'Poweroff:C:sudo shutdown -hP now'
	'Reboot:C:sudo shutdown -r now'
	'Suspend to RAM:C:sudo pm-suspend'
	'Hibernate (Suspend to disk):C:sudo pm-hibernate'
	)

XSERVER_ARGS=(-nolisten tcp)
